version: '3.7'

services:
# --> Reverse proxy
  nginx-proxy:
    image: ${COMPOSE_PROJECT_NAME}_proxy:latest
    container_name: ${COMPOSE_PROJECT_NAME}_proxy
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - portainer
      - postgis
      - homepage
    build:
      context: ./nginx-proxy
    environment:
      - DHPARAM_GENERATION=false
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=hub.ensg-sdi.docker
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      revproxy_apps:
        ipv4_address: 172.24.1.1

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: unless-stopped
    expose:
      - "9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    networks:
      revproxy_apps:
        ipv4_address: 172.24.1.2

  postgis:
    image: postgis/postgis:${POSTGIS_VERSION_TAG:-16-3.4}
    container_name: ensg-sdi-postgis
    expose:
      - "5432"
    environment:
      - "PGUSER=serge"
      - "POSTGRES_USER=serge"
      - "POSTGRES_DB=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - postgis_data:/var/lib/postgresql/data    
    shm_size: 256MB
    networks:
      revproxy_apps:
        ipv4_address: 172.24.1.3

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    expose:
      - "3000"
    volumes:
      - ./homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    networks:
      revproxy_apps:
        ipv4_address: 172.24.1.4

volumes:
  portainer_data:
  postgis_data:
  dns-gen-config:

networks:
  revproxy_apps:
    name: revproxy_apps
    external: true